name: Build and test project

on: [ push ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Install Poetry
        run: poetry install

      - name: Build Poetry
        run: poetry build

      - name: Install Lua environment
        run: ./scripts/install_lua_environment.sh

      - name: Run Lua unit tests and static code analyzer
        run: ./scripts/run_in_conda.sh ./scripts/lua_tests.sh

      - name: Build language container
        run: ./build_language_container.sh

      - name: Start test environment
        run: bash ./scripts/start_integration_test_environment.sh

      - name: Run Python tests
        run: ./scripts/run_in_conda.sh poetry run pytest tests
