name: Run Tests

on:
  workflow_call:
    inputs:
      slow-tests:
        type: boolean
        default: false
      python-version:
        type: string
        required: true

jobs:

  dummy:
    runs-on: ubuntu-latest
    run: true


  # unit-tests:
  #   name: Unit
  #   uses: ./.github/workflows/tests-unit.yml
  #   secrets: inherit
  #   with:
  #     python-version: ${{ inputs.python-version }}

#   integration-tests-without-db:
#     name: iTests (no DB)
#     uses: ./.github/workflows/tests-integration-no-db.yml
#     secrets: inherit
#     with:
#       slow-tests: ${{ inputs.slow-tests }}
#       python-version: ${{ inputs.python-version }}
#
#   integration-tests-with-db:
#     name: iTests with DB
#     uses: ./.github/workflows/tests-integration-db.yml
#     secrets: inherit
#     with:
#       slow-tests: ${{ inputs.slow-tests }}
#       python-version: ${{ inputs.python-version }}
#       exasol-version: ${{ inputs.exasol-version }}
