name: Run Tests

on:
  workflow_call:
    inputs:
      slow-tests:
        type: boolean
        default: false
      python-version:
        type: string
        required: true
      exasol-version:
        type: string
        required: true

jobs:

  unit-tests:
    uses: ./.github/workflows/tests-unit.yml
    secrets: inherit
    with:
      python-version: inputs.python-version

  integration-tests-without-db:
    uses: ./.github/workflows/tests-integration-no-db.yml
    secrets: inherit
    with:
      slow-tests: inputs.slow-tests
      python-version: inputs.python-version

  integration-tests-with-db:
    uses: ./.github/workflows/tests-integration-db.yml
    secrets: inherit
    with:
      slow-tests: inputs.slow-tests
      python-version: inputs.python-version
      exasol-version: inputs.exasol-version
